
export async function fecthUsers() {
   try {
      const response = await 
   } catch (error) {
      console.log("error: " + error)
   }
}